---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysample
spec:
  selector:
    matchLabels:
      app: mysample
  replicas: 2
  template:
    metadata:
      labels:
        app: mysample
    spec:
      containers:
      - name: mysamplecontainer
        image: jigangguo/mysample
        ports:
        - containerPort: 80